### PR TITLE
Edits in "Why sequence models"

### PR DESCRIPTION
**Pull request by VladKha**

### CODE REVIEW

**Comment by mbadry1** [comment]
So, you've skipped the CNN course for now?

**Comment by VladKha** [comment]
@mbadry1 Yep, changed the order a little

**Comment by mbadry1** [comment]
It seems you are more interested in NLP and sequence models areas.

**Comment by mbadry1** [comment]
In the beginning, it was all about the CNN course for me. Then i realized that the sequence models course was more important for my research!

**Comment by VladKha** [comment]
@mbadry1 That's an interesting insight. Thank you!

**Pull request merged**
