### PR TITLE
Edits in "Understanding human-level performance"

### PR DESCRIPTION
**Pull request by VladKha**

### CODE REVIEW

**Comment by mbadry1** [comment]
You've edited `If difference is bigger then its **Avoidable bias**` to `If difference is bigger then its **variance**`
I've updated it back.

**Comment by VladKha** [comment]
@mbadry1 I think, you are a little confused with the wording: in the first case the difference is the avoidable bias and in the second case the difference is the variance. 

So by your rewording, you are saying that "...if the avoidable bias is bigger then avoidable bias..." (same for the variance), which doesn't make a lot of sense.

You can refresh your understanding starting from minute 5 in the corresponding video

**Comment by VladKha** [comment]
@mbadry1 I am very sorry, I confused myself with wording)
Your update was right
Issue resolved

We should probably update the wording to make it even clearer like you suggested in the last comment

**Comment by VladKha** [comment]
Update: addressed it in #114

**Pull request merged**
