### PR TITLE
Edits in "Other regularization methods"

### PR DESCRIPTION
**Pull request by VladKha**

### CODE REVIEW

**Comment by VladKha** [comment]
@mbadry1 I have a question about "Model Ensembles" part in "Other regularization methods" - in the current version of the course there are no videos or materials about this topic in week 1. Were they present when you were taking the course?

**Comment by mbadry1** [comment]
Thank you

**Comment by mbadry1** [comment]
I think you will find a lot of added materials to the notes that i thought its useful.
"Model Ensembles" are one of them. If you want a good video for explaining it, i suggest Stanford CS231n:
http://cs231n.github.io/neural-networks-3/#ensemble

**Comment by VladKha** [comment]
@mbadry1 Thank you for clarifications

**Pull request merged**
